# |  (C) 2008-2023 Potsdam Institute for Climate Impact Research (PIK)
# |  authors, and contributors see CITATION.cff file. This file is part
# |  of MAgPIE and licensed under AGPL-3.0-or-later. Under Section 7 of
# |  AGPL-3.0, you are granted additional permissions described in the
# |  MAgPIE License Exception, version 1.0 (see LICENSE file).
# |  Contact: magpie@pik-potsdam.de

################################################################################
# Define internal functions
################################################################################

fsecScenario <- function(scenario) {

  source("config/default.cfg")

  # Version number
  v <- "v36_FSEC"

  x <- list(c_BAU            = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = "FSEC", "RCP60"),
            d_SSP1bau        = list(standard = c("cc", "SSP1", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "SSP1")),
            d_SSP1PLUSbau    = list(standard = c("cc", "SSP1", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP26", "SSP1",
                                  "energy", "bioplastics", "population", "institutions", "timberCities")),
            d_SSP2bau        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "SSP2")),
            d_SSP3bau        = list(standard = c("cc", "SSP3", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP70", "SSP3")),
            d_SSP4bau        = list(standard = c("cc", "SSP4", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "SSP4")),
            d_SSP5bau        = list(standard = c("cc", "SSP5", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP85", "SSP5")),
            # FSDP (all transformations active)
            e_FSDP = list(standard = c("cc", "SSP1", "NDC", "ForestryEndo"), # or SSP2?
                                  fsec = c("FSEC", "RCP19",
                                  "energy", "bioplastics", "population", "institutions", "timberCities",
                                  "awms", "livestock", "nueMAC", "riceMAC", "biodiversity", "fairTrade", "capitalSubst", "minWage",
                                  "REDDaff", "REDD", "landscapeElements", "landSharing", "landSparing", "waterSparing", "peatland",
                                  "soil", "allDietAndWaste", "allEnvPrice", "RCP19", "SSP1energy")),
            # FSDPs (without external)
            d_SSP1fsdp       = list(standard = c("cc", "SSP1", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP26", "SSP1",
                                  "awms", "livestock", "nueMAC", "riceMAC", "biodiversity", "fairTrade", "capitalSubst", "minWage",
                                  "REDDaff", "REDD", "landscapeElements", "landSharing", "landSparing", "waterSparing", "peatland",
                                  "soil", "allDietAndWaste", "allEnvPrice", "RCP26")),
            d_SSP2fsdp       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "SSP2",
                                  "awms", "livestock", "nueMAC", "riceMAC", "biodiversity", "fairTrade", "capitalSubst", "minWage",
                                  "REDDaff", "REDD", "landscapeElements", "landSharing", "landSparing", "waterSparing", "peatland",
                                  "soil", "allDietAndWaste", "allEnvPrice", "RCP26")),
            d_SSP3fsdp       = list(standard = c("cc", "SSP3", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "SSP3",
                                  "awms", "livestock", "nueMAC", "riceMAC", "biodiversity", "fairTrade", "capitalSubst", "minWage",
                                  "REDDaff", "REDD", "landscapeElements", "landSharing", "landSparing", "waterSparing", "peatland",
                                  "soil", "allDietAndWaste", "allEnvPrice", "RCP26")),
            d_SSP4fsdp       = list(standard = c("cc", "SSP4", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "SSP4",
                                  "awms", "livestock", "nueMAC", "riceMAC", "biodiversity", "fairTrade", "capitalSubst", "minWage",
                                  "REDDaff", "REDD", "landscapeElements", "landSharing", "landSparing", "waterSparing", "peatland",
                                  "soil", "allDietAndWaste", "allEnvPrice", "RCP26")),
            d_SSP5fsdp       = list(standard = c("cc", "SSP5", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "SSP5",
                                  "awms", "livestock", "nueMAC", "riceMAC", "biodiversity", "fairTrade", "capitalSubst", "minWage",
                                  "REDDaff", "REDD", "landscapeElements", "landSharing", "landSparing", "waterSparing", "peatland",
                                  "soil", "allDietAndWaste", "allEnvPrice", "RCP26")),
            # Individual transformation clusters:
            a_Population         = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "population")),
            a_EconDevelop        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "institutions")),
            a_EnergyTrans        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP26", "energy", "RCP26")),
            a_Bioplastics        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "bioplastics")),
            a_CapitalSubst       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "capitalSubst")),
            a_MinWage            = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "minWage")),
            a_NoUnderweight      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "noUnderweight")),
            a_HalfOverweight       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "halfOverweight")),
            a_DietVegFruitsNutsSeeds  = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "fruitsNutsVegSeeds")),
            a_DietMonogastrics   = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "monogastrics")),
            a_DietRuminants      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP45", "ruminants")),
            a_DietLegumes        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "pulses")),
            a_DietEmptyCals      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "processed")),
            a_DietFish           = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "fish")),
            a_LessFoodWaste      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "waste")),
            a_ManureMngmt        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "awms")),
            a_LivestockMngmt     = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "livestock")),
            a_CropeffTax         = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "cropefficiency")),
            a_NitrogenEff        = list(standard = c("cc", "rcp7p0", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "nueMAC")),
            a_RiceMit            = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "riceMAC")),
            a_BiodivSparing      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "biodiversity")),
            a_LiberalizedTrade   = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "fairTrade")),
            a_TimberCities       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "timberCities")),
            a_REDDaff            = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "REDDaff")),
            a_REDD               = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "REDD")),
            a_CropRotations      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "landSharing")),
            a_LandscapeElements  = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "landscapeElements")),
            a_LandSparing        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "landSparing")),
            a_WaterSparing       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "waterSparing")),
            a_PeatlandSparing    = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "peatland")),
            a_SoilCarbon         = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                        fsec = c("FSEC", "RCP60", "soil")),
            # Scenarios (combinations of transformation clusters)
            b_ExternalPressures   = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP26", "population", "institutions", "energy", "bioplastics", "timberCities", "SSP1energy")),
            b_WaterSoil           = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "waterSparing", "soil")),
            b_REDDaffRuminants    = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "ruminants", "REDDaff")),
            b_DietRotations       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "landSharing", "allDiet")),
            b_MonogastricsRotations = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "landSharing", "monogastrics")),
            b_TradeRotations      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "landSharing", "fairTrade")),
            b_TradeREDDaff        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "REDDaff")),
            b_TradeSoil           = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "soil")),
            b_TradeMonogastrics   = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "monogastrics")),
            b_TradeRuminants      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "ruminants")),
            b_TradeVeggies        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "fruitsNutsVegSeeds")),
            b_MonogastricsVeggies = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "monogastrics", "fruitsNutsVegSeeds")),
            b_SoilMonogastric     = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "monogastrics", "soil")),
            b_SoilMonogastricRuminants = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "monogastrics", "ruminants","soil")),
            b_SoilRotations       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "landSharing", "soil")),
            b_LivestockManureMngmt = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "livestock", "awms")),
            b_LivestockNUEMngmt   = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "livestock", "nueMAC")),
            b_AllNitrogen         = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "awms", "nueMAC", "monogastrics", "ruminants", "waste")),
            b_AllClimate          = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "nueMAC", "riceMAC", "awms", "allEnvPrice")),
            b_FullBiodiv          = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "biodiversity", "landSharing")),
            b_AllEnvironment      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "biodiversity", "REDDaff",
                                          "landSparing", "waterSparing", "peatland", "soil", "allEnvPrice")),
            b_AllHealth           = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "allDiet")),
            b_AllInclusion        = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "population", "institutions", "timberCities", "fairTrade", "capitalSubst", "minWage")),
            b_Livelihoods         = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "capitalSubst", "minWage")),
            b_LivelihoodsExt      = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "fairTrade", "capitalSubst", "minWage", "bioplastics", "energy", "timberCities")),
            b_Bioeconomy          = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "bioplastics", "energy", "timberCities")),
            b_AgroMngmt           = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "landSharing", "landscapeElements", "nueMAC", "riceMAC", "livestock", "awms", "soil")),
            b_Efficiency          = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "awms", "waste", "fairTrade", "nueMAC")),
            b_Diet                = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "allDietAndWaste")),
            b_Protection          = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP60", "waterSparing", "landSparing", "peatland")),
            b_NatureSparing       = list(standard = c("cc", "SSP2", "NDC", "ForestryEndo"),
                                  fsec = c("FSEC", "RCP45", "waterSparing", "landSparing", "peatland", "biodiversity", "REDDaff"))
            )
  # Assign selected scenario to cfg
  cfg <- setScenario(cfg, x[[scenario]]$standard)
  cfg <- setScenario(cfg, x[[scenario]]$fsec, scenario_config = "config/scenario_fsec.csv")

  # Download gridded population data
  gms::download_unpack(input = "FSEC_populationScenarios_v2_22-08-22.tgz",
                       targetdir = "./input",
                       repositories = cfg$repositories)
  # Download gridded RCP temperature data
  gms::download_unpack(input = "FSEC_GlobalSurfaceTempPerRCP_v2_16-01-23.tgz",
                       targetdir = "./input",
                       repositories = cfg$repositories)

  # general
  cfg$title       <- paste(v, scenario, sep = "")
  cfg$recalibrate <- FALSE
  cfg$qos         <- "standby_maxMem_dayMax"
  cfg$output      <- c("extra/highres",
                       "extra/disaggregation",
                       "projects/FSEC_nitrogenPollution",
                       "projects/FSEC_cropDiversityGrid",
                       "projects/FSEC_dietaryIndicators",
                       "projects/FSEC_costs",
                       "projects/FSEC_water",
                       "rds_report_iso",
                       "rds_report")
  cfg$force_download  <- TRUE
  cfg$gms$s80_optfile <- 1

  return(cfg)
}
