*** |  (C) 2008-2018 Potsdam Institute for Climate Impact Research (PIK),
*** |  authors, and contributors see AUTHORS file
*** |  This file is part of MAgPIE and licensed under GNU AGPL Version 3
*** |  or later. See LICENSE file or go to http://www.gnu.org/licenses/
*** |  Contact: magpie@pik-potsdam.de

*' @description In the affore_vegc_dec16 realisation, the forestry land can increase
*' in size due to afforestation.
*' The incentive for afforestation is cost reduction through generation of
*' negative carbon emissions. If a carbon price is applied on carbon emissions,
*' negative emissions return a negative cash flow, reducing global production costs.
*' Negative emissions on forestry land can be generated by increasing carbon stocks through afforestation.
*' In general an afforestation activity takes places if the benefits outweigh the costs (NPV > 0)
*' based on a investment horizon of 30 years (`s32_planing_horizon`) defined in [12_interest_rate].

*' @limitations forestry sector is static over time

*####################### R SECTION START (PHASES) ##############################
$Ifi "%phase%" == "sets" $include "./modules/32_forestry/affore_vegc_dec16/sets.gms"
$Ifi "%phase%" == "declarations" $include "./modules/32_forestry/affore_vegc_dec16/declarations.gms"
$Ifi "%phase%" == "input" $include "./modules/32_forestry/affore_vegc_dec16/input.gms"
$Ifi "%phase%" == "equations" $include "./modules/32_forestry/affore_vegc_dec16/equations.gms"
$Ifi "%phase%" == "preloop" $include "./modules/32_forestry/affore_vegc_dec16/preloop.gms"
$Ifi "%phase%" == "presolve" $include "./modules/32_forestry/affore_vegc_dec16/presolve.gms"
$Ifi "%phase%" == "postsolve" $include "./modules/32_forestry/affore_vegc_dec16/postsolve.gms"
*######################## R SECTION END (PHASES) ###############################
