---
title: "NPI/NDC policies"
author: "MAgPIE"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magpie)
library(reshape2)
library(knitr)
clean_indc <- function(x) {
  x[getRegions(which(x[,,"policy"] == 0,arr.ind = TRUE)),,] <- NA
  #x <- x[,,"targettype",invert=TRUE]
  indc_true <- sort(unique(getRegions(which(x[,,"policy"] == 1,arr.ind = TRUE))))
  x <- x[indc_true,,]
  x <- x[,,"policy",invert=TRUE]
  getNames(x,dim=1) <- c("Ref","BaseYear","EndYear","Target")
  x <- as.data.frame(x)
  x$Cell <- NULL
  x$Year <- NULL
  x <- dcast(x, Region ~ Data1, value.var="Value")
  return(x)
}
npi_pol_deforest <- read.magpie("policies/npi_pol_deforest.csv")
npi_pol_afforest <- read.magpie("policies/npi_pol_afforest.csv")
npi_pol_emis     <- read.magpie("policies/npi_pol_emis.csv")
ndc_pol_deforest <- read.magpie("policies/ndc_pol_deforest.csv")
ndc_pol_afforest <- read.magpie("policies/ndc_pol_afforest.csv")
ndc_pol_emis     <- read.magpie("policies/ndc_pol_emis.csv")
```

## Reduced deforestation (%)
percentage reduction: 0 = no reduction, 1 = full reduction of deforestation

Ref: BaseYear (1), BAU scenario (2)

```{r AD, results='asis'}
options(knitr.kable.NA = '')
cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{NPI}
      \\centering",
        kable(clean_indc(npi_pol_deforest),digits = 2,format = "latex",booktabs=TRUE,linesep = c("")),
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{NDC}",
        kable(clean_indc(ndc_pol_deforest),digits = 2,format="latex",booktabs=TRUE,linesep = c("")),
    "\\end{minipage} 
\\end{table}
\\newpage"
))  
```


## Afforestation (Mha)
Ref: BaseYear (1), BAU scenario (2)

```{r AFF, results='asis'}
options(knitr.kable.NA = '')
cat(c("\\begin{table}[ht]
    \\begin{minipage}{.5\\linewidth}
      \\caption{NPI}
      \\centering",
        kable(clean_indc(npi_pol_afforest),digits = 2,format = "latex",booktabs=TRUE,linesep = c("")),
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{NDC}",
        kable(clean_indc(ndc_pol_afforest),digits = 2,format="latex",booktabs=TRUE,linesep = c("")),
    "\\end{minipage} 
\\end{table}
\\newpage"
))  
```

## CO2 emission reduction (%)
percentage reduction: 0 = no reduction, 1 = full reduction of CO2 emissions from deforestation

Ref: BaseYear (1), BAU scenario (2)

```{r EMIS, results='asis'}
options(knitr.kable.NA = '')
kable(clean_indc(npi_pol_emis),digits = 2,caption = "NPI")
kable(clean_indc(ndc_pol_emis),digits = 2,caption = "NDC")
```
